### PR TITLE
refactor for platform compatibility

### PR DESCRIPTION
**Pull request by DarhkVoyd**
### **Updates:**  
1. Fix the paths as they used '\' instead of '/'.
2. The original name was too long and complex to execute in terminal easily so renamed it to simply covers.py

### CODE REVIEW

**Comment by DarhkVoyd** [comment]
Also I was getting:

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

adding "ssl._create_default_https_context = ssl._create_unverified_context"
solved the issue

**Comment by DarhkVoyd** [comment]
@Zorklis kindly review this pull request

**Comment by Zorklis** [comment]
> @Zorklis kindly review this pull request

Not sure why I was called here, since I only submitted one or two covers for PS1/PSX and that was with xlenore's helpful hand. I do have the power to commit on ps2 project but I don't have the knowledge/expertise in this area, hope someone helps you out :)

**Comment by DarhkVoyd** [comment]
> > @Zorklis kindly review this pull request
> 
> Not sure why I was called here, since I only submitted one or two covers for PS1/PSX and that was with xlenore's helpful hand. I do have the power to commit on ps2 project but I don't have the knowledge/expertise in this area, hope someone helps you out :)

I apologise for the misunderstanding, I saw you as as active collaborator.

**Comment by DarhkVoyd** [comment]
@xlenore kindly review

**Comment by xlenore** [comment]
> @xlenore kindly review

Sorry for my inactivity, I will be updating the code of the 2 projects soon

**Pull request merged**
